name: ceremony
description: Ceremony ID Multitool App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  google_fonts:
  encrypt:
  ntp:
  foil:
  get:
  hexcolor:
  flutter_secure_storage:
  flutter_nfc_kit:
  ndef:
  pin_code_fields:
  ionicons: ^0.2.1
  iconsax: ^0.0.8
  intl:
  flutter:
    sdk: flutter

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/ddsl.png
