name: ceremony
description: Ceremony ID Multitool App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  google_fonts: ^3.0.1
  encrypt: ^5.0.1
  ntp: ^2.0.0
  foil: ^0.9.0+1
  get: ^4.6.5
  hexcolor: ^2.0.7
  flutter_secure_storage: ^5.1.2
  flutter_nfc_kit: ^3.3.1
  ndef: ^0.3.1
  pin_code_fields: ^7.4.0
  ionicons: ^0.2.1
  iconsax: ^0.0.8
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  local_auth: ^2.1.2
  flutter_svg: ^1.1.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9

flutter_native_splash:
  image: lib/assets/ddsl.png
  color: '#1e4e82'
  
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: lib/assets/logo.png
  adaptive_icon_foreground: lib/assets/foreground.png

flutter:
  uses-material-design: true

  assets:
    - lib/assets/ddsl.png
    - lib/assets/cer.svg
    - lib/assets/nfc.svg
